### ISSUE TITLE
Not launching when I enter an HTML file

### ISSUE THREAD

**Issue by waivek** [yaegassy/coc-tailwindcss3#28] opened 2023-05-11 22:21 UTC
This is my CocInfo when I enter a *.html file

```
## versions

vim version: VIM - Vi IMproved 9.0 9000447
node version: v16.13.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: C:\Users\vivek\vimfiles\plugged\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2023-05-12T03:49:19.049 INFO (pid:19708) [plugin] - coc.nvim initialized with node: v16.13.0 after 455
2023-05-12T03:49:37.418 INFO (pid:19708) [attach] - receive notification: showInfo []


```

This is my `tailwind.config.js`

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['*.html'],
  theme: {
    extend: {},
  },
  plugins: [],
}

```

Am I making some simple mistake? I've followed the installation instructions.

**Comment by yaegassy** [comment] 2023-05-11 23:56
Please check the TIPS section of the README. It may be related to the issue at hand. https://github.com/yaegassy/coc-tailwindcss3#tips

**Comment by waivek** [comment] 2023-05-12 10:41
Thank you for the fast reply. I had followed all the tips before posting the issue. Would a screen recording help in debugging?

![tailwindlsp_v01](https://github.com/yaegassy/coc-tailwindcss3/assets/5134623/f4dce501-330c-4063-aa05-0ea4462e9aad)

**Comment by yaegassy** [comment] 2023-05-12 22:13
Thank you for the screenshot. However, unfortunately I don't understand the cause. Just to confirm, is `@yaegassy/coc-tailwindcss3` installed correctly?

Since the extension doesn't seem to be working, it might not be possible to execute, but if you run the `:CocCommand tailwindCSS.showOutput` command, will it display any results?

**Comment by waivek** [comment] 2023-05-13 09:23
`@yaegassy/coc-tailwindcss3` is installed. I'm not sure how to verify if it's installed correctly. 

Here is a gif of me running `CocInstall @yaegassy/coc-tailwindcss3`

![tailwindlsp_v03](https://github.com/yaegassy/coc-tailwindcss3/assets/5134623/adb69e90-482d-44a5-8ceb-358d1c9ee4f0)

I then verify that Coc knows about it by tabbing through the `:CocUninstall` options. I press ESCAPE and run `:CocCommand tailwindCSS.showOutput` which gives me a blank result as shown by the next gif:


![tailwindlsp_v02](https://github.com/yaegassy/coc-tailwindcss3/assets/5134623/89e23018-2bf2-426d-a8e3-ab2eddbffa8c)

**Comment by yaegassy** [comment] 2023-05-15 02:08
Thanks for the information. 🙇  I tried it in a Windows environment and was able to reproduce the phenomenon that the language server does not start up correctly.

However, since I don't use Windows very often, it may take some time to make adjustments, etc. I would like to find some time to proceed with the adjustments.

**Comment by yaegassy** [comment] 2023-05-15 03:36
We have fixed this issue. Please try upgrading coc-tailwindcss3 (v0.5.3) and see if it resolves the problem.

**Comment by waivek** [comment] 2023-05-15 10:06
![image](https://github.com/yaegassy/coc-tailwindcss3/assets/5134623/9a663538-7402-4cc0-bcf8-3b9ca67e9cc7)

Yess, it's working! Thank you so much for resolving this so quickly!!

**Comment by yaegassy** [comment] 2023-05-15 10:27
Thanks for testing it, I will close this issue.

**Closed as completed by yaegassy** 2023-05-15 10:27 UTC
